CREATE TABLE HISTORIALCOMPRAS(
ID_COMPRA CHAR(8) NOT NULL,
PROVEDOR VARCHAR(20) NOT NULL,
FECHA_COMPRA DATE NOT NULL,
TOTAL_COMPRA CHAR(5) NOT NULL);


DELIMITER //

CREATE TRIGGER InsertarCompras
AFTER INSERT
ON compras FOR EACH ROW
BEGIN
INSERT INTO COMPRAS
(ID_COMPRA,PROVEDOR,FECHA_COMPRA,TOTAL_COMPRA)
SELECT ID_COMPRA,PROVEDOR,FECHA_COMPRA,TOTAL_COMPRA FROM HISTORIALCOMPRAS;
END
//
DELIMITER ;
